server:
  port: 8086

spring:
  application:
    name: message-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:}

rocketmq:
  name-server: ${ROCKETMQ_NAMESRV:127.0.0.1:9876}

management:
  endpoints:
    web:
      exposure:
        include: health,info
