server:
  port: 8083

spring:
  application:
    name: trade-service
  datasource:
    url: jdbc:mysql://192.168.201.100:3306/game_trade?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.201.100:8848
        namespace: 

rocketmq:
  name-server: 192.168.201.100:9876
  producer:
    group: trade-producer-group

management:
  endpoints:
    web:
      exposure:
        include: health,info
